CLANG_TIDY_BIN ?= clang-tidy-18
CLANG_UML_BIN ?= ~/devel/clang-uml/debug/src/clang-uml
CLANG_UML_OPTS ?= 

OS_UNAME := $(shell uname -s)
ifeq ($(OS_UNAME),Linux)
	SDKROOT ?= 
else ifeq ($(OS_UNAME),Darwin)
	SDKROOT ?= $(shell xcrun --show-sdk-path) 
endif

.DEFAULT_GOAL := all
.PHONY: all

all:
	~/devel/waf-2.1.4/waf --version && \
	~/devel/waf-2.1.4/waf configure clangdb && \
	SDKROOT=$(SDKROOT) $(CLANG_TIDY_BIN) -p build src/hello.cc && \
	$(CLANG_UML_BIN) $(CLANG_UML_OPTS)
