out = 'build'

def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('compiler_cxx')
	conf.load('clang_compilation_database')

def build(bld):
	bld.program(source='src/hello.cc', target='app', cxxflags=['-std=c++17'])
