out = 'build'

def options(opt):
	opt.load('compiler_cxx')
	opt.load('clang_compilation_database')#, tooldir='~/devel/waf-2.1.4/waflib/extras')

def configure(conf):
	conf.load('compiler_cxx')
	conf.load('clang_compilation_database')#, tooldir='~/devel/waf-2.1.4/waflib/extras')

def build(bld):
	bld.program(source='src/hello.cc', target='app', cxxflags=['-std=c++17'])