include ../Makefile.ccj

print_version_cmd = buck2 --version

generate_compdb = \
	buck2 init && \
	SDKROOT=$(SDKROOT) $(BUILD_FLAGS) buck2 build "//:hello[compilation-database]" && \
	COMP_DB=$$(buck2 targets --show-json-output "//:hello[compilation-database]" | jq -r '."root//:hello[compilation-database]"'); cp $$COMP_DB . && \
	jq '.[] |= (.directory = "${PWD}/buck2")' compile_commands.json | sponge compile_commands.json
