CLANG_TIDY_BIN ?= clang-tidy-18
CLANG_UML_BIN ?= ~/devel/clang-uml/debug/src/clang-uml

.DEFAULT_GOAL := all
.PHONY: all

all:
	bazel --version && \
	bazel run :refresh_compile_commands && \
	$(CLANG_TIDY_BIN) src/hello.cc && \
	$(CLANG_UML_BIN)