CLANG_TIDY_BIN ?= clang-tidy-18
CLANG_UML_BIN ?= ~/devel/clang-uml/debug/src/clang-uml
CLANG_UML_OPTS ?= 

OS_UNAME := $(shell uname -s)
ifeq ($(OS_UNAME),Linux)
	SDKROOT ?= 
else ifeq ($(OS_UNAME),Darwin)
	SDKROOT ?= $(shell xcrun --show-sdk-path) 
endif


.DEFAULT_GOAL := all
.PHONY: all

all:
	meson --version && \
	meson setup builddir && \
	SDKROOT=$(SDKROOT) $(CLANG_TIDY_BIN) -p builddir src/hello.cc && \
	$(CLANG_UML_BIN) -d builddir $(CLANG_UML_OPTS)
