CLANG_TIDY_BIN ?= clang-tidy-18
CLANG_UML_BIN ?= ~/devel/clang-uml/debug/src/clang-uml

.DEFAULT_GOAL := all
.PHONY: all

all:
	premake5 --version && \
	git clone git@github.com:MattBystrin/premake-ecc.git ecc || true && \
	premake5 ecc && \
	$(CLANG_TIDY_BIN) src/hello.cc && \
	$(CLANG_UML_BIN)