CLANG_TIDY_BIN ?= clang-tidy-18
CLANG_UML_BIN ?= ~/devel/clang-uml/debug/src/clang-uml

.DEFAULT_GOAL := all
.PHONY: all

all:
	scons --version && \
	scons compile_commands.json && \
	$(CLANG_TIDY_BIN) src/hello.cc && \
	$(CLANG_UML_BIN)